import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';

const MAX_ENTRIES = 3_500;
const GRID_CELL_DEGREES = 5;
// Budgets derived from measured output (~59 KB gzip at 3500 entries); keep
// the module small enough for offline bundling. Target ≈ +10%, cap ≈ +25%.
const GZIP_TARGET_BYTES = 64_700;
const GZIP_HARD_LIMIT_BYTES = 73_500;
const OUTPUT_URL = new URL('../src/generated/cities.ts', import.meta.url);
const require = createRequire(import.meta.url);

function isValidEntry(entry) {
  const coordinates = entry && entry.loc && entry.loc.coordinates;
  return (
    typeof entry.name === 'string' &&
    entry.name.length > 0 &&
    typeof entry.country === 'string' &&
    /^[A-Z]{2}$/.test(entry.country) &&
    Number.isFinite(entry.population) &&
    entry.population > 0 &&
    Array.isArray(coordinates) &&
    Number.isFinite(coordinates[0]) &&
    Number.isFinite(coordinates[1]) &&
    coordinates[1] >= -90 &&
    coordinates[1] <= 90 &&
    coordinates[0] >= -180 &&
    coordinates[0] <= 180
  );
}

function compareCities(a, b) {
  return (
    b.population - a.population ||
    (a.name < b.name ? -1 : a.name > b.name ? 1 : 0) ||
    (a.country < b.country ? -1 : a.country > b.country ? 1 : 0) ||
    a.loc.coordinates[0] - b.loc.coordinates[0] ||
    a.loc.coordinates[1] - b.loc.coordinates[1]
  );
}

function selectCities(allCities) {
  const valid = allCities.filter(isValidEntry);

  // Pass 1: guarantee geographic coverage — keep the largest city of every
  // grid cell that contains any city, so rural areas still get a nearby town.
  const bestPerCell = new Map();
  for (const city of valid) {
    const [lon, lat] = city.loc.coordinates;
    const key = `${Math.floor(lon / GRID_CELL_DEGREES)}:${Math.floor(lat / GRID_CELL_DEGREES)}`;
    const current = bestPerCell.get(key);
    if (!current || compareCities(city, current) < 0) {
      bestPerCell.set(key, city);
    }
  }
  const guaranteed = new Set(bestPerCell.values());

  // Pass 2: fill the remainder by population, descending.
  const selected = [...guaranteed];
  for (const city of [...valid].sort(compareCities)) {
    if (selected.length >= MAX_ENTRIES) {
      break;
    }
    if (!guaranteed.has(city)) {
      selected.push(city);
    }
  }

  return selected.sort(compareCities).map((city) => ({
    name: city.name,
    country: city.country,
    lat: Math.round(city.loc.coordinates[1] * 1e3) / 1e3,
    lon: Math.round(city.loc.coordinates[0] * 1e3) / 1e3,
  }));
}

function renderModule(cities) {
  return [
    '// Generated by npm run generate:cities. Do not edit manually.',
    '// Source: GeoNames (cities with population >= 1000) via all-the-cities@3.1.0.',
    '// all-the-cities is MIT licensed; underlying GeoNames data is CC BY 4.0.',
    'export interface CityEntry {',
    '  /** City name, e.g. "Berlin" */',
    '  name: string;',
    '  /** ISO 3166-1 alpha-2 country code, e.g. "DE" */',
    '  country: string;',
    '  lat: number;',
    '  lon: number;',
    '}',
    `export const CITIES: readonly CityEntry[] = ${JSON.stringify(cities)};`,
    '',
  ].join('\n');
}

async function generateModule() {
  const allCities = require('all-the-cities');
  const cities = selectCities(allCities);

  if (cities.length === 0) {
    throw new Error('all-the-cities produced an empty selection.');
  }

  return renderModule(cities);
}

function enforceGzipBudget(output) {
  const gzipBytes = gzipSync(output).length;

  if (gzipBytes > GZIP_TARGET_BYTES) {
    console.warn(
      `Warning: generated cities module is ${gzipBytes} bytes gzip, above ${GZIP_TARGET_BYTES}-byte target (${GZIP_HARD_LIMIT_BYTES}-byte hard cap).`,
    );
  }

  if (gzipBytes > GZIP_HARD_LIMIT_BYTES) {
    throw new Error(
      `Generated cities module is ${gzipBytes} bytes gzip, exceeding ${GZIP_HARD_LIMIT_BYTES}-byte hard cap.`,
    );
  }
}

async function checkGeneratedModule(expected) {
  let actual;

  try {
    actual = await readFile(OUTPUT_URL);
  } catch (error) {
    if (error && error.code === 'ENOENT') {
      console.error('Generated cities module is missing. Run `npm run generate:cities` to regenerate it.');
      process.exitCode = 1;
      return;
    }
    throw error;
  }

  if (!actual.equals(Buffer.from(expected, 'utf8'))) {
    console.error('Generated cities module is stale. Run `npm run generate:cities` to regenerate it.');
    process.exitCode = 1;
    return;
  }

  console.log('Generated cities module is up to date.');
}

async function main() {
  const args = process.argv.slice(2);
  const check = args.length === 1 && args[0] === '--check';

  if (args.length > 0 && !check) {
    console.error('Usage: node scripts/generate-cities.mjs [--check]');
    process.exitCode = 2;
    return;
  }

  const output = await generateModule();
  enforceGzipBudget(output);

  if (check) {
    await checkGeneratedModule(output);
    return;
  }

  await mkdir(dirname(fileURLToPath(OUTPUT_URL)), { recursive: true });
  await writeFile(OUTPUT_URL, output, 'utf8');
  console.log('Generated src/generated/cities.ts.');
}

await main();
